export const products = [
  {
    id: 1,
    title: "Refreshing Mint",
    price: "30,000 MMK",
    discount: "20,000MMK",
    points: "600 Points",
    image: "/pod-black.jpg",
  },
  {
    id: 2,
    title: "Refreshing Mint",
    price: "30,000 MMK",
    discount: "20,000MMK",
    points: "600 Points",
    image: "/pod-blue.jpg",
  },
  {
    id: 3,
    title: "Refreshing Mint",
    price: "30,000 MMK",
    discount: "20,000MMK",
    points: "600 Points",
    image: "/pod-green.jpg",
  },
  {
    id: 4,
    title: "Refreshing Mint",
    price: "30,000 MMK",
    discount: "20,000MMK",
    points: "600 Points",
    image: "/pod-purple.jpg",
  },
  {
    id: 5,
    title: "Refreshing Mint",
    price: "30,000 MMK",
    discount: "20,000MMK",
    points: "600 Points",
    image: "/pod-redpink.jpg",
  },
  {
    id: 6,
    title: "Refreshing Mint",
    price: "30,000 MMK",
    discount: "20,000MMK",
    points: "600 Points",
    image: "/pod-white.jpg",
  },
];
